---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository

metadata:
  name: backend-api
  namespace: flux-system
spec:
  image: ghcr.io/klebeer/code-challenge/backend-api
  interval: 1m0s
  secretRef:
    name: pullsecret
